spring.datasource.url=jdbc:oracle:thin:@//<your-oracle-rds-hostname>:1521/cads
spring.datasource.username=your-username
spring.datasource.password=your-password
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
